version: '3.8'

services:

  lb1:
    build: lb1/
    container_name: lb1
    networks:
      - cluster
    privileged: true
    ports:
      - "8081:80"
    environment:
      - NODE=lb1
      - VIRTUAL_HOST=10.0.0.100

  lb2:
    build: lb2/
    container_name: lb2
    networks:
      - cluster
    privileged: true 
    ports:
      - "8082:80"
    environment:
      - NODE=lb2
      - VIRTUAL_HOST=10.0.0.100

  backend1:
    build: backend1/
    container_name: backend1
    privileged: true
    networks:
      cluster:
        aliases:
          - backend1

  backend2:
    build: backend2/
    container_name: backend2
    privileged: true
    networks:
      cluster:
        aliases:
          - backend2

  host:
    build: ansible/
    container_name: ansible
    networks:
      cluster:
        aliases:
          - ansible
    depends_on:
      - lb1
      - lb2
      - backend1
      - backend2
    privileged: true
    volumes:
      - ./ansible/ansible:/ansible
      

networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24